_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 300

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
check_val_every_n_epoch: 5

precision: 16

# ckpt path
resume_from_checkpoint: null
