_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 55

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
#val_check_interval: 1.0
check_val_every_n_epoch: 10

# ckpt path
resume_from_checkpoint: null

replace_sampler_ddp: False