# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: ray.yaml
  - model: adnerf.yaml
  - callbacks: null
  - logger: tensorboard.yaml
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# rendering options
options:
  n_samples_per_ray_coarse: 64
  n_samples_per_ray_fine: 128
  neareast_distance: 0.6417311906814576
  farthest_distance: 1.2417311906814574
  sampling_linearly_in_disparity: True
  white_background: False

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/Obama/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: ???
