# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: ray.yaml
  - model: adnerf.yaml
  - callbacks: null
  - logger: tensorboard.yaml
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# rendering options
render_hparams:
  n_samples_coarse: 64
  n_samples_fine: 128
  near_bound: 0.6417311906814576
  far_bound: 1.2417311906814574
  audio_smoothing_size: 8
  white_background: False
  fps: 25

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/Obama/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: ???
